[tool.poetry]
name = "bubble_feedback"
version = "0.1.0"
description = ""
authors = ["Jay Joshi <joshijayk1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
quart = "^0.10.0"
quart-cors = "^0.2.0"
hypercorn = "^0.9.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
